{% set name = "mikeio" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f62cbb889a94edf9e2e45b9e8c52b2c7d62100a14e247f4af762e2bb1843fbf

build:
  skip: true  # [not win or py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pythonnet
    - numpy
    - pandas
    - scipy
    - pyyaml
    - shapely
    - xarray
    - matplotlib-base
    - tqdm
    - pyproj

test:
  imports:
    - mikeio

about:
  home: https://github.com/DHI/mikeio
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  summary: API for the DHI MIKE file types
  description: Read, write and manipulate dfs0, dfs1, dfs2, dfs3, dfsu and mesh files. Read res1d and xns11 files.
  dev_url: https://github.com/DHI

extra:
  recipe-maintainers:
    - ecomodeller
    - georgebv
